const path = require('path');
const fs = require('fs');

// This is the standalone server generated by Next.js
const serverPath = path.join(__dirname, '.next', 'standalone', 'server.js');

if (fs.existsSync(serverPath)) {
    // Hostinger provides the PORT environment variable
    process.env.PORT = process.env.PORT || 3000;
    process.env.HOSTNAME = '0.0.0.0';

    console.log(`Starting Next.js standalone server on port ${process.env.PORT}...`);
    require(serverPath);
} else {
    const http = require('http');
    console.error('Next.js standalone server not found! Please make sure to run "npm run build" first.');

    // Start a dummy server so Hostinger doesn't show a 503 error immediately
    http.createServer((req, res) => {
        res.writeHead(200, { 'Content-Type': 'text/plain' });
        res.end('Application is starting up or requires a build. Check back in a minute.');
    }).listen(process.env.PORT || 3000);
}
